# fly.toml app configuration file generated for full-stack-open-pokedex-purple-morning-4542 on 2025-08-10T15:23:00+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'full-stack-open-pokedex-purple-morning-4542'
primary_region = 'fra'

[deploy]
  strategy = "canary"

[env]
  PORT = "8080" 

[processes]
  app = "node app.js" 

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
